### ISSUE TITLE
Consider publishing on npm

### ISSUE THREAD

**Issue by Sebazzz** [Daddoon/Blazor.Polyfill#11]
Have you considered publishing the library on npm? This would offer (for the consumers) the ability to keep it up to date, and keep compiled/minified code out of the repository.

**Comment by Daddoon** [comment]
You are right it may be a good idea.
I'm not very used to NPM, as i mainly work with NuGet an C# things, but i think this is something doable.

I'm on vacation, but i will take a look to this next week.

**Comment by Sebazzz** [comment]
Thanks for considering 👍

Met vriendelijke groet,
Sebastiaan Dammann
________________________________
Van: Guillaume ZAHRA <notifications@github.com>
Verzonden: Friday, October 25, 2019 6:47:18 PM
Aan: Daddoon/Blazor.Polyfill <Blazor.Polyfill@noreply.github.com>
CC: Sebastiaan Dammann <sebastiaandammann@outlook.com>; Author <author@noreply.github.com>
Onderwerp: Re: [Daddoon/Blazor.Polyfill] Consider publishing on npm (#11)


You are right it may be a good idea.
I'm not very used to NPM, as i mainly work with NuGet an C# things, but i think this is something doable.

I'm on vacation, but i will take a look to this next week.

**Comment by Daddoon** [comment]
Maybe not perfect about NPM integration, but done.

See here:

https://www.npmjs.com/package/blazor.polyfill

Don't hesitate to tell me if this is not working out of the box with NPM, i don't know yet how to use it properly.

**Comment by Sebazzz** [comment]
Yes, it works good :) Just installed and used it in my project.

One small request for the next version: Publish the non-minified file as well for development purposes. It is better than to dig into a minified file if issues occur in Internet Explorer.

**Comment by Daddoon** [comment]
Oopsies, as the package builder asked me what was the main file, i assumed to just include one.
I will take a look on this very soon and ship an update on NPM (even if there is no code update)

**Comment by Daddoon** [comment]
A new release has been done on NPM (nothing change otherwise in the code). The release on NPM include now the unminified version.
