### ISSUE TITLE
npm does not include unminified version

### ISSUE THREAD

**Issue by Daeymon** [Daddoon/Blazor.Polyfill#15]
Firstly, thankyou for setting this up on npm, this will make it easier to monitor and maintain updates through the libman.json. One request though, could the npm release include the unminified version in addition to the already provided minified version of the script file? I know for myself and my organisation, its generally preferred to use unminified versions on Development environments.

**Comment by Daddoon** [comment]
I think i can do a thing about this, so i will post an update very soon with the unminified version.

**Comment by Daddoon** [comment]
Done ! Check if everything is right !
