### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by daver77** [Daddoon/Blazor.Polyfill#21]
Is this correct, you have 2 includes of the same file

`<script type="text/javascript">
    if (/MSIE \d|Trident.*rv:/.test(navigator.userAgent)) {
        document.write('<script src="js/blazor.polyfill.min.js"><\/script>');
    }
</script>
**_<script type="text/javascript" src="blazor.polyfill.min.js"></script>_**
<script src="_framework/blazor.server.js"></script>`

**Comment by Daddoon** [comment]
You are correct, it's a typo error ! Thanks for noticing !
I will fix that ! Thanks !
