### ISSUE TITLE
Error with TelerikDatePicker Blazor component

### ISSUE THREAD

**Issue by daver77** [Daddoon/Blazor.Polyfill#22]
Hi, we use the Telerik [Calendar](https://demos.telerik.com/blazor-ui/calendar/overview) control which works fine with the polyfill but the [DatePicker](https://demos.telerik.com/blazor-ui/datepicker/overview) throws an error. Any idea what the error could be? Here's a link to the [telerik-blazor.js](https://demos.telerik.com/blazor-ui/_content/telerik.ui.for.blazor/js/telerik-blazor.js).

[2019-11-25T10:16:17.594Z] Error: Microsoft.JSInterop.JSException: Object doesn't support this action
TypeError: Object doesn't support this action
   at value (https://localhost:44377/_content/telerik.ui.for.blazor/js/telerik-blazor.js:37:8083)
   at value (https://localhost:44377/_content/telerik.ui.for.blazor/js/telerik-blazor.js:37:7870)
   at e (https://localhost:44377/_content/telerik.ui.for.blazor/js/telerik-blazor.js:37:4215)
   at r (https://localhost:44377/_content/telerik.ui.for.blazor/js/telerik-blazor.js:1:5739)
   at o (https://localhost:44377/_content/telerik.ui.for.blazor/js/telerik-blazor.js:37:2442)
   at Anonymous function (https://localhost:44377/_framework/blazor.server.js:8:28731)
   at Promise (https://localhost:44377/js/blazor.polyfill.js:8904:7)
   at e.jsCallDispatcher.beginInvokeJSFromDotNet (https://localhost:44377/_framework/blazor.server.js:8:28701)
   at Anonymous function (https://localhost:44377/_framework/blazor.server.js:1:19139)
   at e.prototype.invokeClientMethod (https:/

**Comment by Daddoon** [comment]
With just this stacktrace i cannot tell if the Polyfill is the error.
Does your component work on other browser ?

But what come to my mind is two possible cases:

- Your component use some ECMAScript syntax that may not be supported by IE11, wich has an old JS engine. Remember that even on blazor.server.js version, Javascript is still executed through the browser, but correct me if i'm wrong.
- It may also show that there is a missing functionnality / polyfill for a specific feature, on IE11.

Wich version of the Polyfill do you use ? The last one ?

**Comment by Daddoon** [comment]
Seeing your stacktrace, it would be better to set IE11 debugger to **Stop at each exception** mode, and then put a breakpoint just before the code that goes in exception.

Then i imagine you should be able to see which closure/function/feature is missing on an object compared to other browsers.

In my opinion, it must not be something unfixable.

**Comment by daver77** [comment]
I'm using 3.0.1, yeah it works in proper browsers. 

Here's what it breaks on

![image](https://user-images.githubusercontent.com/2369739/69540390-669bbd80-0f7e-11ea-82aa-d8698abc6f72.png)

**Comment by Daddoon** [comment]
In my opinion this is not a lack of polyfill for Blazor, but only the fact that telerik use IntersectionObserver and IE11 may not support it.

Can you try to add the following polyfill to your project and confirm it is working on IE11 then:

https://github.com/w3c/IntersectionObserver/blob/master/polyfill/README.md

**Comment by daver77** [comment]
Yeah I don't think it's a Blazor issue, it seems there may be a few extra polyfills I need to add.

**Comment by Daddoon** [comment]
Can you tell me if my suggestion resolve this issue ? If yes, maybe i will add some additional notes in the README of the project, for any person using Telerik component with Blazor.

**Comment by daver77** [comment]
It got past that error but there's more I need, still working on it

**Comment by Daddoon** [comment]
Tell me where this is going if you go through your errors ;) !

**Comment by daver77** [comment]
I got to this, the page now loads without Blazor disconnecting. The TelerikDatePicker dropdown does not work though and does not error but you can type in the box and the change events fire so that will do me for now.

`        if (/MSIE \d|Trident.*rv:/.test(navigator.userAgent)) {
            document.write('<script src="https://polyfill.io/v3/polyfill.min.js?features=Element.prototype.closest%2CIntersectionObserver%2Cdocument.querySelector"><\/script>');
            document.write('<script src="/js/blazor.polyfill.min.js"><\/script>');
        }`

**Comment by Daddoon** [comment]
Thanks for your report! The last missing thing may be CSS related ?
Otherwise i will update the README with your info for Telerik component, as i don't want to add too much thing in the Blazor.Polyfill package itself, but using Telerik component on IE11 for Blazor is a good thing!

Closing !

**Comment by Daddoon** [comment]
Updated the README

**Comment by mcbride-clint** [comment]
More of a question for @daver77, but have you made any progress on the CSS incompatibility with Telerik Components in IE.  Seems like all the Dropdown, Combobox, DatePicker popups have the same issue.  

Doesn't seems to be javascript incompatibility unless there is some ignored errors somewhere.  I have been trying make some javascript events to open and show the animation containers but they behave strongly sometimes.

**Comment by daver77** [comment]
@mcbride-clint no sorry, my app was internal for the company so I just forced them to use Chrome!

**Comment by mcbride-clint** [comment]
Wish I could get my company to switch our primary browser to Chrome

I was able to work out the issue with the JS/CSS.  When they are invoking their show command they are setting the display style to null which IE is ignoring.  I copied out their JS file and formatted it find the lines and changed the display change to empty string("") and now dropdowns and datepickers show as expected.  

Working on the keyboard navigation now.  It looks like it's a Blazor command that is not working correctly.

**Comment by icnocop** [comment]
> I was able to work out the issue with the JS/CSS. When they are invoking their show command they are setting the display style to null which IE is ignoring. I copied out their JS file and formatted it find the lines and changed the display change to empty string("") and now dropdowns and datepickers show as expected.

I think I'm also experiencing this issue with Telerik's data grid column filter menu.

@mcbride-clint do you have a "diff" with the specific changes you made to make it work?

Thank you!

**Comment by mcbride-clint** [comment]
That MSBuild Task it a really cool way to do that. We were having some issue with some components on 2.19 so we are still on 2.18.  I cannot get a copy of our edited file but I copied out our instructions that I have been leaving at the top of the file as we were upgrading.

2.18
List of Custom Fixes to implement again in later versions
Animation Show and ShowAsync replaced display = null with display = "" for IE compatibility
Replace `display = null` with `display = ""`
TranslateKeyName translate IE KeyboardNames to new standard 
Replace `this.name += t.name` with `this.Name += TranslateKeyName(t.key)`

```
function TranslateKeyName(name){
  switch (name) {
    case "Down":
      return "ArrowDown";
    case "Up":
      return "ArrowUp";
    case "Left":
      return "ArrowLeft";
    case "Right":
      return "ArrowRight";
  }
}
```

**Comment by Daddoon** [comment]
Thanks all for your contribution !

If you sort this in order to give a workaround / "How To" guide to make TelerikDatePicker implementation easy, feel free to do a PR on this project README, as it may be usefull for other people too.

**Comment by icnocop** [comment]
Just to follow up, I was able to resolve my issue by adding 
```
        library: "TelerikBlazor",
        libraryTarget: "window"
```

Here's the result:
```
const path = require('path');

module.exports = {
    mode: "production",
    entry: {
        'telerik.ui.for.blazor/3.4.0/telerik-blazor': './wwwroot/js/telerik.ui.for.blazor/3.4.0/telerik-blazor.js'
    },
    output: {
        path: path.resolve(__dirname, 'wwwroot/js'),
        filename: "[name].es5.js",
        library: "TelerikBlazor",
        libraryTarget: "window"
    },
    target: ['web', 'es5'],
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        presets: [
                            ['@babel/preset-env', {
                                targets: {
                                    "ie": "11"
                                }
                            }]
                        ]
                    }
                }
            }
        ]
    },
}
```

In `<head>` in `_Layout.cshtml`:
```
<script src="https://polyfill.io/v3/polyfill.min.js?version=3.111.0&features=Object.getOwnPropertyNames%2CObject.assign%2CElement.prototype.closest%2Cdocument.querySelector"></script>
<script src="~/js/telerik.ui.for.blazor/3.4.0/telerik-blazor.es5.js"></script>
```

**Comment by Daddoon** [comment]
Good if you have found a solution about this.
I tried to implement something to do this semi-automatically through the **ES5ConversionScope** option, listed [here](https://github.com/Daddoon/Blazor.Polyfill#additional-options)

Maybe i should add more description about this option.
When this value is enabled, Blazor.Polyfill will try to convert to an ES5 compliant version of a JS file and will write it in a es5module folder (if i remember this right) at the root of your project. Also the SHA of the source file will be written on the converted destination file, and so the conversion to ES5 will be done again only if the source file changed.

When this is enabled, no need to manually target to the es5module folder that was created, as a HTTP handler on the server will automatically serve the ES5 version of your file transparently. Of course all of this work only when the file is hosted in your app, not on a CDN.

First boot should of your app should be longer, or if a dependency change, as it will try to make a ES5 version at least once that will be cached in your project.

This should prevent to manually doing thing, and also this is working when you don't have the control to the access to a JS file, like a JS file that is loaded dynamically through a RCL (Razor Class Library).

I canno't guarantee that this will work with any scenario. I didn't have issue at the moment on my projects btw.
