### ISSUE TITLE
MatBlazor component polyfills

### ISSUE THREAD

**Issue by danikf** [Daddoon/Blazor.Polyfill#23]
Hi,
"forEach" polyfills are missing for MatBlazor components (RadioButton). Simmilar issue as for Telerik. Could be mentioned somewhere?

These additional polyfills seams to solve the issue with MatBlazor.MatRadioGroup / MatRadioButton:

https://polyfill.io/v3/polyfill.min.js?features=Array.prototype.forEach%2CNodeList.prototype.forEach

Thanks for your work,
D

**Comment by Daddoon** [comment]
Thanks for the info !

I will try to make an update in few days, adding what you mentionned.

**Comment by Daddoon** [comment]
I just seen that i had already mentionned some workaround at the bottom of the Blazor.Polyfill documentation about wich polyfills to add for Telerik.

I added your additionals Polyfills in the Polyfill.io URI at the bottom of the documentation, see the updated README.

You may use this URL instead: https://polyfill.io/v3/polyfill.min.js?features=Element.prototype.closest%2CIntersectionObserver%2Cdocument.querySelector%2Cfeatures=Array.prototype.forEach%2CNodeList.prototype.forEach

Here the updated documentation part: https://github.com/Daddoon/Blazor.Polyfill#using-telerik-blazor-component-on-ie11

Thanks for your suggestion !
Closing.
