### ISSUE TITLE
Broken in 5.0.100-preview.1 (server) for IE11

### ISSUE THREAD

**Issue by princeoffoods** [Daddoon/Blazor.Polyfill#24]
Hi, just wanted to let you know that the polyfill is not working with the current preview in Blazor Server on IE11.

Errors from the Console:
Error: Failed to complete negotiation with the server: ReferenceError: 'AbortController' is undefined
Error: Failed to start the connection: ReferenceError: 'AbortController' is undefined

I tried adding AbortController from polyfill.io but then the next set of errors appears:
Error: There was an error applying batch 2.
Error: There is no browser renderer with ID 0

Hopefully it will be possible to have some support for IE11 in 5.0 too.
Thanks!

**Comment by Daddoon** [comment]
Thanks for the report.

I'm actually very busy so i will not be able to look at this directly.
However if you debug and find wich polyfill or property is missing at runtime in Blazor for IE11, let me informed !

**Comment by princeoffoods** [comment]
Will keep trying. Thank you for starting this project!

**Comment by Daddoon** [comment]
This has been fixed.

Please download from [GitHub Blazor.Polyfill 3.0.8 release page](https://github.com/Daddoon/Blazor.Polyfill/releases/tag/3.0.8) or from [Blazor.Polyfill on NPM](https://www.npmjs.com/package/blazor.polyfill) or simply by calling **npm i blazor.polyfill**

Actually used this polyfill: https://github.com/mo/abortcontroller-polyfill
And needed to import it early with webpack with a patched fetch, as stated in the doc:

```
import 'abortcontroller-polyfill/dist/polyfill-patch-fetch'
```

**Comment by princeoffoods** [comment]
Thanks, works great!
