### ISSUE TITLE
server side IE11 check

### ISSUE THREAD

**Issue by dorssel** [Daddoon/Blazor.Polyfill#28]
As a suggestion for the README: alternatively to the client side conditional <script> as mentioned in the INSTALLATION section, the server could do it:
``` 
@{
    // IE11 compatibility
    if (Request.Headers.TryGetValue("User-Agent", out var userAgents)
        && (userAgents.FirstOrDefault() is string userAgent)
        && System.Text.RegularExpressions.Regex.IsMatch(userAgent, @"MSIE \d|Trident.*rv:"))
    {
        <script src="js/blazor.polyfill.min.js"></script>
    }
}
```

**Comment by Daddoon** [comment]
Very good suggestion !

I imagine that you have tested this yourself !
Do you mind to make a PR for this change / additions in the README ?

Otherwise i will try to do it later.

**Comment by dorssel** [comment]
Yes, I tested it, but only on .NET Core 3.1, and the syntax is C# 8.0.
I am not sure what the scope is for Blazor.Polyfill... is it also .NET Core 2.1? (it defaults to C# 7.0 syntax)
