### ISSUE TITLE
Integration of ESRI Arcgis JS API conflicts with polyfill

### ISSUE THREAD

**Issue by BerndNierula** [Daddoon/Blazor.Polyfill#29]
Hi Daddoon

I  build a small mapping app based on the vs 2019 (v16.6.1) server template. The map is created using <script src="https://js.arcgis.com/4.12/"></script> 
So far this worked fine on clientside Blazor and works also serverside on Chrome and Edge browser (Win10). Unfortunately in IE11 the map is not displayed. Fiddler tells me, that map requests are sent to the mapping server...
My organisation still uses IE11 for many Intranet business applications, so before introducing Blazor I must have at least a basic support for IE11

Could you please have a look at this issue, hope this is a small problem. Please tell me, if you need some additional information, the VS solutiont etc.

Thank you very much.

Best Regards
Bernd Nierula

**Comment by Daddoon** [comment]
Before looking anything can you validate that you are able to launch arcgis on IE11, even without Blazor ?

See:

- https://developers.arcgis.com/javascript/latest/guide/system-requirements/index.html
- https://gis.stackexchange.com/questions/158643/arcgis-javascript-api-not-working-in-ie-11-js-api-1-6
- https://developers.arcgis.com/javascript/3/jshelp/supported_browsers.html

Otherwise, do you have any error messages in the log of IE11 ?

**Comment by BerndNierula** [comment]
Thank's a lot for your reply. I khow, that ESRI's support for IE11 is limited, especially 3D funktions don't work well. But in my case I need very basic 2D mapping, which should work.

My example is basically a copy of an ESRI sample, which works very well in IE11. See

- https://developers.arcgis.com/javascript/latest/sample-code/sandbox/index.html?sample=intro-mapview

In my blazor server solution IE11 doesn't show any messages in console or debug window.

Please tell me if you need some more information.

**Comment by Daddoon** [comment]
Sorry, but i don't have a lot of time for now to test why it doesn't work with ARCGIS.
My advice if you want to fix this by yourself would be to:

- Inspect the Polyfills packages included in the project
- Try to add them separately by themselves in your project, one to one.
- See when you ARGIS plugin break.

This way you will at least identify wich Polyfill seems to break your plugin.

Also is arcgis called before or after the blazor.polyfill.js script ? Can you inverse the script order, in case it change something ?

**Comment by Daddoon** [comment]
Closing as no feedback.
