### ISSUE TITLE
Object.freeze: argument not an Object

### ISSUE THREAD

**Issue by DSBhogal** [Daddoon/Blazor.Polyfill#31]
Currently running into a series of errors on load of my server side Blazor application, I tried including the additional polyfills for Object.freeze but doesn't fix the issue - any ideas?

![image](https://user-images.githubusercontent.com/33750091/84655598-25163400-af09-11ea-9196-a54569ae4b1d.png)

![image](https://user-images.githubusercontent.com/33750091/84655919-bc7b8700-af09-11ea-89e2-d9f622a65fa7.png)

**Comment by Daddoon** [comment]
Actually away this week. I will take a look next week. Did you try to add the missing polyfill in the source code for webpack ?

Also is your error occurring on a default Blazor template ?

Thanks !

**Comment by DSBhogal** [comment]
No worries, I'll be honest I'm completely new to polyfills only started looking into them since i encountered these issues. Didn't look into adding the missing polyfill to source code, wouldn't know where to start. The project started off on a default blazor template if that helps but has changed drastically

**Comment by Daddoon** [comment]
Ok ! I'm asking only to know if this error is related directly to something missing for Blazor or if this is due to a third party library that does not correlate with Blazor polyfills minimum requirement.

**Comment by DSBhogal** [comment]
Ah right on initially i thought it was to do with something for Blazor but I believe it is for PayPal so no bother. I did try to add the extra polyfills in but that didn't solve the issue. I'll close this as it isn't an issue on your side - thank you anywya for your help
