### ISSUE TITLE
Legacy Edge support for server-side

### ISSUE THREAD

**Issue by Daddoon** [Daddoon/Blazor.Polyfill#39]
Legacy Edge support for server-side

- [ ] Need a Windows 10 VM with Edge Legacy installed for testing - So Edge with EdgeHTML engine.

**Comment by Daddoon** [comment]
For information support to me:

@benm-eras said:

> @Daddoon I don't know if you have access to one, but my MSDN subscription provides access to ISO files all versions of Windows 10 back to 1511. Also Azure has images for "Windows 10 Enterprise 2016 LTSB" and 1809 which should have legacy Edge.
>
> Regarding IE11 and WASM, that is what I expected, and was actually the reason we're using server over WASM.
>
> I have confirmed that your recent changes do indeed work in IE11. Thank you again!

**Comment by Daddoon** [comment]
@benm-eras I'm still a Microsoft MVP atm, up to August 2021 if i'm not renewed, so i have a MSDN subscription too so it should not be a problem.

But so, you are saying that the "Windows 10 Enterprise 2016 LTSB" and 1809 versions of Windows would be sufficient for testing ?

**Comment by benm-eras** [comment]
@Daddoon well the 2016 one should definitely come with legacy Edge, and I am pretty sure 1809 should be pre-chromium edge too. as long as you don't update them they should be fine.

**Comment by benm-eras** [comment]
@Daddoon I am afraid that I think I may have been a bit premature in my declaration that it was working in IE11. I based that assumption on the navigation between pages working, but on closer inspection I think that it is just making normal HTTP requests when clicking on links. Also I am getting several errors in the Dev tools:

![image](https://user-images.githubusercontent.com/30234297/101016376-9ce02580-3560-11eb-8574-c6244e76a5c3.png)

**Comment by Daddoon** [comment]
I did not have any error on my side.
Also it seem that there is a missing "forEach" property, i don't know if it's a missing polyfill or due to something else.

Do you have a repro step and a repro project to send ?
Also if you can post this informations (screenshot here included) on the IE11 issue instead.

**Comment by benm-eras** [comment]
@Daddoon sorry, it was my mistake, I deleted my comment, which I guess I shouldn't have done because it's orphaned yours.

Ironically the missing `forEach` was caused by the script loaded from `https://polyfill.io/v3/polyfill.js` which I had added after testing your polyfill earlier (trying to get Bootstrap 5 to work with IE11 now!). 

I think I need some coffee...

**Comment by Daddoon** [comment]
Did you have the same kind of exceptions on IE11 if you remove the polyfill from polyfill.io ? I mean does IE11 crash entirely ?

**Comment by benm-eras** [comment]
When I removed the call to polyfill.io all errors from the console disappeared, and explicitly adding features to the request also cleared the errors:

`https://polyfill.io/v3/polyfill.min.js?features=Array.prototype.forEach%2CNodeList.prototype.forEach`

It wasn't a problem with your polyfill. sorry for the confusion

**Comment by Daddoon** [comment]
I think some polyfills may conflict if put together. I actually used some kind of specific polyfills because it seem they worked better on IE11 where some other one was crashing.

But it's true that additional work is needed on IE11 when adding new features to your requirement.

**Comment by lca85** [comment]
Not working on 
Microsoft Edge 41.16299.1004.0
Microsoft EdgeHTML 16.16299
navigator.userAgent
output: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299"
Work arround:
On Blazor.Polyfill.Server.HttpRequestExtensions

private static bool IsInternetExplorer(string userAgent)
        {
            // this can be done better. More error safe.
            // And I dont know the version in wich edge swiched to chromium engine
            bool IsEdgeless16 = userAgent.Contains("Edge/") ?int.Parse(userAgent.Split("Edge/")[1].Split('.')[0])<=16 : false;
            return userAgent.Contains("MSIE")
                   || userAgent.Contains("Trident")
                   || IsEdgeless16;
        }

**Comment by lca85** [comment]
Can we have this change in Blazor.Polyfill.Server.HttpRequestExtensions
private static bool IsInternetExplorer(string userAgent)
        {
            
            return userAgent.Contains("MSIE")
                   || userAgent.Contains("Trident")
                   || userAgent.Contains("Edge");
        }
"Microsoft selected the Edg token to avoid compatibility issues that may be caused by using the string Edge, which is used by the version of Microsoft Edge based on EdgeHTML. The Edg token is also consistent with existing tokens used on iOS and Android."

**Comment by Daddoon** [comment]
@Ica85 Thanks for the feedback (talking about your removed post), and for your investigation.

Even if will try to create a VM in order to test old Edge behavior, yes i think we can integrate this update that seem pretty trivial and efficient.

As you stated, and i have tested on the Chromium Edge, yes, the UserAgent is Edg on Chromium instead of Edge, so we are safe here.

I will surely implement this differently, like this, just in case of future changes:

```cs
         private static bool IsInternetExplorer(string userAgent)
        {   
            return userAgent.Contains("MSIE")
                   || userAgent.Contains("Trident");
        }

         //This is about Edge Legacy / EdgeHTML, not the new Chromium one
         private static bool IsEdgeHTML(string userAgent)
        {
            return userAgent.Contains("Edge");
        }

        private static bool BrowserNeedES5Fallback(string userAgent) {
               return IsInternetExplorer(userAgent)
                      || IsEdgeHTML(userAgent);
        }
```

Of course, the method used on the **MapWhen** methods call in the Http request management will rely now on **BrowserNeedES5Fallback** instead of **IsInternetExplorer**.

Will try to ship something else like this tomorrow, as it seem fast to fix and test (except the VM installation).
The only caveat today is that we can't determine if the calling page is a server-side or WASM page.

Not a problem here for server-side of course, but if we want to try to manage the WASM mode in the future on EdgeHTML, we must detect it as the blazor.polyfill.js file, by default, give some issues on EdgeHTML if used when in WASM mode.

Maybe trying to "analyze" the starting page in the pipeline. btw, maybe something to think in the future if there is demand and possibilities for WASM on EdgeHTML, not sure yet.

**Comment by lca85** [comment]
@Daddoon  Couldn’t agree more. :)

**Comment by Daddoon** [comment]
This is fixed internally. I'm trying to add some other fixes before shipping. I will close this issue when the update is shipped

**Comment by Daddoon** [comment]
I have made Edge Legacy support for the next version that i will ship shortly, and also fixed the reconnection behavior missing on Edge and IE11: Some API /polyfill were missing for this and a try catch in the blazor.server.js file was i think somehow silently avoiding the real errors to be shown in the browser.

**Comment by Daddoon** [comment]
Update shipped !

- Nuget page: https://www.nuget.org/packages/BlazorPolyfill.Server/5.0.100.1
- Some additional informations on the updated doc: https://github.com/Daddoon/Blazor.Polyfill
- Release page here: https://github.com/Daddoon/Blazor.Polyfill/releases/tag/5.0.100.1

> - Add **Edge Legacy** (EdgeHTML engine) support
> - Fix missing reconnection modal behavior on **Internet Explorer 11** and **Edge Legacy**
> - Add pre-caching of all files needed for this library at the first web app request, in order to prevent further requests to wait for file generation on the server before serving the app. This mean that, now, if the app page is shown, then everything is ready.

Closing the issue !
