### ISSUE TITLE
NullReferenceException IsInternetExplorer

### ISSUE THREAD

**Issue by DavidDeSloovere** [Daddoon/Blazor.Polyfill#46]
There is currently no null check in `Blazor.Polyfill.Server.HttpRequestExtensions.IsInternetExplorer(string userAgent)`. 
We found that out the hard way after health checks from HA Proxy reported the application was down. This was because HA Proxy sends a HEAD request that does not have a User-Agent header by default.
If you want, I can submit a PR for this.

**Comment by Daddoon** [comment]
Thanks for the feedback.

Sorry, i may be used to the old behavior i known about .NET Framework and HTTP request, where accessing unexisting keys would create them instead.

But you are right, i missed to check Headers on this place. Sorry for the inconveniance.
Yes i'm open to the PR if you can submit it, i will then publish it shortly as it can be critical.

**Comment by Daddoon** [comment]
Also, if you are using the latest version of BlazorPolyfill.Server package, the same issue should be here for Edge Lecgacy check.

**Comment by Daddoon** [comment]
The shipping will come in a few minutes

**Comment by DavidDeSloovere** [comment]
Thanks for the quick follow up.

**Comment by Daddoon** [comment]
Seemed critical to me !
Should be available now: https://www.nuget.org/packages/BlazorPolyfill.Server/5.0.100.2
