### ISSUE TITLE
Blazor (Server-side) not work in Internet Explorer 10-11

### ISSUE THREAD

**Issue by GwtLabs** [Daddoon/Blazor.Polyfill#5]
When running Blazor (Server-side) with Blazor.Polyfill.js in browser Internet Explorer 11

    <script src="blazor.polyfill.min.js"></script>
    <script src="_framework/blazor.server.js"></script>

 attached, I get these errors:

> Information: Normalizing '_blazor' to 'http://localhost:20183/_blazor'.
> Information: WebSocket connected to ws://localhost:20183/_blazor?id=87ybIVTPb7Vwq3Ui4qNpkw
> Information: Using HubProtocol 'messagepack'.
> Error: Error parsing handshake response: TypeError: Object doesn't support property or method 'indexOf'
> SCRIPT5022: Error parsing handshake response: TypeError: Object doesn't support property or method 'indexOf'
> blazor.server.js (16,10932)
> Error: Connection disconnected with error 'Error: Error parsing handshake response: TypeError: Object doesn't support property or method 'indexOf''.

Is it possible to fix it in some way?

**Comment by Daddoon** [comment]
Hi,

I’m on holiday.
I didn’t have tested the server side version, and will take a look in 2
weeks.

IndexOf should be a pretty standard thing in my opinion, the included
polyfills should be sufficient. Websocket is normally supported on IE11.
Did you try with src="./blazor.polyfill.min.js" ?

Are you having 200 or a 404 code in your browser ?

**Comment by GwtLabs** [comment]
The file blazor.polyfill.min.js is loaded correctly. I also tried as you suggested.
![image](https://user-images.githubusercontent.com/3123616/45586385-011e5c80-b8f7-11e8-84bc-bc630ea174ac.png)

**Comment by Daddoon** [comment]
I will take a look when coming back from Holidays. We still need to
determine what is really faulty.

**Comment by Swellenator** [comment]
I also have this issue using the latest server side blazor sample app. Would be great if you could have a look at it.

**Comment by Daddoon** [comment]
The different issues in order to make it works on IE11 has been found.
With some additionnals required polyfills (a TypedArray polyfill, and a HTML5 template polyfill for IE11), i was able to launch the Blazor demo app without problems.

I will update and close this thread when i will release an update this evening !
The fix will be available in the release tab then.

**Comment by Daddoon** [comment]
Fixed in [0.3.0](https://github.com/Daddoon/Blazor.Polyfill/releases/tag/0.3.0) !
Enjoy !
