### ISSUE TITLE
IE11: Cannot redefine non-configurable property 'find'

### ISSUE THREAD

**Issue by sven5** [Daddoon/Blazor.Polyfill#60]
With the current release 3.0.8 for .NET Core 3.1 I'm getting this error in IE11.

```
SCRIPT5078: Cannot redefine non-configurable property "find"
es.symbol.js (266,1)
```

Could help here?

Thanks

**Comment by Daddoon** [comment]
Do you have a reproductive scenario for this error ?
I never encountered it in my tests.

This is maybe a bug in an older version of **core-js** bundled in this project, or a messy implementation of a third party polyfill.
Some hints here: https://github.com/zloirock/core-js/issues/790

It would be interesting that i have a reproductive scenario, as i would also test on the last Blazor server versions in .NET 5.0.

I would then ship an update to for both .NET 3.x and .NET 5.0 if i find the issue.

**Comment by sven5** [comment]
Hi @Daddoon 

Thanks for your fast reply. I'm just investigating this issue and it seems that quill js is causing trouble here.

`<script type="text/javascript" src="~/lib/quill/dist/quill.js"></script>`

I registered quill before your polyfill lib and that seems to be wrong. When placing the quill reference after polyfill then it works.

**Comment by Daddoon** [comment]
I think that **quill.js** may have it's own **find** polyfill internally, that is applied if the required **find** signature is not found.

Seems that there is some interactions between the two libs, i think one or the other (quill.js or the core-js part) does react as expected while finding an existing signature.

What's happening here i think is that by placing your file after the blazor.polyfill lib make your quill.js lib not trying to implement the **find** signature, as it has been found previously.

Nothing blocking, i can close this i suppose !
