### ISSUE TITLE
IE11 - When parent element contains img tag element as child element with access the parent element innerHTML property value script error thrown

### ISSUE THREAD

**Issue by pandiyarajm93** [Daddoon/Blazor.Polyfill#64]
In my scenario, I need to get the innerHTML value of an contenteditable element

My sample parent element contains an IMG tag element as a child. 
specific button clicks action I need to get the parent element innerHTML property value. while doing this action getting below highlighted console error in a console window

_Facing issue in Blazor Server app with contenteditable div element_

![image](https://user-images.githubusercontent.com/54373337/109290169-475ca180-784d-11eb-864d-429d39560ce6.png)

any workaround to avoid this error logs ?

**Comment by Daddoon** [comment]
From what you sent me, i cannot be sure that this is issue is related to Blazor.Polyfill, as it may be an other IE11 missing thing.
Also your explanation is vague for me.

Do you have a minimalistic repro project or code that i can eventually test ?

**Comment by pandiyarajm93** [comment]
My component is a complex one, I will create and share the issue reproducible minimalistic sample

**Comment by pandiyarajm93** [comment]
Unable to reproduce the issue with separate sample, so i am closing this issue now.

If found reproducible steps, will reopen it with sample.

**Comment by Daddoon** [comment]
Fair enough ! 😄
