### ISSUE TITLE
ServerSide Blazor doesn't work with IE11 (Preview4)

### ISSUE THREAD

**Issue by chrdlx** [Daddoon/Blazor.Polyfill#7]
Just to let you know this doesn't work anymore with the latest Preview 4.  As far as I can see there're no errors in the IE11 console.  I'd love to help but I have pretty basic JS knowledge.
Regards

**Comment by Daddoon** [comment]
I will try to make a look to this, this week

**Comment by chrdlx** [comment]
This fix is being tracked here
https://github.com/aspnet/AspNetCore/issues/9436

Which involves changes in the blazor's framework code, not just polyfills.
