### ISSUE TITLE
Unable to click buttons on Blazor.Polyfil 6.0.200 for IE11 on Microsoft Surface RT

### ISSUE THREAD

**Issue by mikaelsundin** [Daddoon/Blazor.Polyfill#81]
Buttons does not call c# code when clicked when using version 6.0.200 on Microsoft Surface RT.
If i downgrade to version 6.0.100.3 the button works as expected and is calling the c# code.

# Step to reproduce
* Create new Blazor app from sample in VS2022
* Add nuget Blazor.Polyfil 6.0.200 
* Start the sample and connect from IE11 on Microsoft Surface RT.

**Comment by Daddoon** [comment]
Thanks for the informations.

- Is the bug occuring on a regular IE11, or only on the Microsoft Surface RT IE11 ?
- Do you have any log / error / stacktrace you can forward from the IE11 debug console ?
- Are you using Blazor.Polyfill with the **UsePackagedBlazorServerLibrary ** option set to true or set to false ?

**Comment by Daddoon** [comment]
Thanks for your answer.

I will also try on my side simple scenarios, when i have some time, as i'm out for nearly 2 weeks.
As Surface RT / Windows RT is not virtualizable, it will be difficult to debug this if it occur only on this, and i don't have any Windows RT Devices.

Also, as you have a problematic exemple project, could you mind to post the repro project here ? As a zip or a repo i can fork, depend what you prefer.

Thanks !

**Comment by mikaelsundin** [comment]
It work now when i create a new project. Probably IE11 has cached some files somewhere or VS2022 have done something wrong. 
Also my old project is working when i update to latest...

Not a bug then :) Great project 👍

**Comment by Daddoon** [comment]
Thanks for the feedback @mikaelsundin !

No problem, maybe something gone wrong with the cache as some internal things changed for the cache validation.
By the way, in the future if you have any doubt, even if i don't have tested (yet) the behavior for this, you may try to append a parameter to the blazor.server.js file (and same for blazor.polyfill), like:

```html
<script src="_framework/blazor.polyfill.min.js?v=1"></script>
<script src="_framework/blazor.server.js?v=1"></script>
```

Of course change this parameter anytime by something else, if you want to be sure to invalidate the cache between 2 versions. The cache invalidation should be automatic from the server side, but if you have any doubt or side effect about this, adding a random parameter to theses attribute should always invalidate from the web browser side, as the browser will consider that this is a completly new file reference thanks to this different parameter.
